export const placesData = [
  {
    id: 1,
    name: "Calibre Coffee Roasters",
    address: "Jl. Walikota Mustajab No. 67-69, Genteng",
    category: "Coffee Shop",
    noiseScore: 2,
    rating: 4.8,
    reviewCount: 1240,
    tags: ["#quiet", "#work-friendly", "#aesthetic"],
    photo: "/images/calibre.png",
    isFeatured: true,
    wifi: true, ac: true, powerOutlet: true,
    priceRange: "Rp25-50k",
    hours: "10:00 - 22:00",
    crowdStatus: "sepi",
    mapsUrl: "https://maps.google.com/?q=Calibre+Coffee+Roasters+Surabaya"
  },
  {
    id: 2,
    name: "Space K Cafe & Library",
    address: "Jl. Raya Darmo Permai III No. 54, Sukomanunggal",
    category: "Cafe & Library",
    noiseScore: 1,
    rating: 4.7,
    reviewCount: 876,
    tags: ["#quiet", "#cozy", "#buku"],
    photo: "/images/spacek.png",
    isFeatured: true,
    wifi: true, ac: true, powerOutlet: true,
    priceRange: "Rp20-40k",
    hours: "10:00 - 22:00",
    crowdStatus: "sedang",
    mapsUrl: "https://maps.google.com/?q=Space+K+Cafe+Surabaya"
  },
  {
    id: 3,
    name: "NugaSpace",
    address: "Jl. Marina Emas No. 73, Keputih, Sukolilo",
    category: "Coworking Space",
    noiseScore: 1,
    rating: 4.9,
    reviewCount: 2100,
    tags: ["#quiet", "#produktif", "#worth-it"],
    photo: "/images/nugaspace.png",
    isFeatured: true,
    wifi: true, ac: true, powerOutlet: true,
    priceRange: "Rp15k/jam",
    hours: "08:00 - 23:00",
    crowdStatus: "sepi",
    mapsUrl: "https://maps.google.com/?q=NugaSpace+Surabaya"
  },
  {
    id: 4,
    name: "AADK Coffee & Eatery",
    address: "Jl. Tegalsari No. 58, Tegalsari",
    category: "Coffee Shop",
    noiseScore: 3,
    rating: 4.6,
    reviewCount: 1580,
    tags: ["#work-friendly", "#cozy", "#ramai"],
    photo: "/images/aadk.png",
    isFeatured: false,
    wifi: true, ac: true, powerOutlet: true,
    priceRange: "Rp20-45k",
    hours: "09:00 - 23:00",
    crowdStatus: "ramai",
    mapsUrl: "https://maps.google.com/?q=AADK+Coffee+Tegalsari+Surabaya"
  },
  {
    id: 5,
    name: "Koridor Coworking (Siola)",
    address: "Gedung Siola Lt.3, Jl. Tunjungan No. 1, Genteng",
    category: "Coworking Space",
    noiseScore: 2,
    rating: 4.5,
    reviewCount: 950,
    tags: ["#gratis", "#quiet", "#produktif"],
    photo: "/images/koridor.png",
    isFeatured: false,
    wifi: true, ac: true, powerOutlet: true,
    priceRange: "Gratis",
    hours: "08:00 - 16:00",
    crowdStatus: "ramai",
    mapsUrl: "https://maps.google.com/?q=Koridor+Coworking+Space+Siola+Surabaya"
  },
  {
    id: 6,
    name: "Satu Atap Coworking",
    address: "Jl. Pacar No. 2, Genteng",
    category: "Coworking Space",
    noiseScore: 2,
    rating: 4.6,
    reviewCount: 720,
    tags: ["#aesthetic", "#quiet", "#worth-it"],
    photo: "/images/satuatap.png",
    isFeatured: false,
    wifi: true, ac: true, powerOutlet: true,
    priceRange: "Rp15k/jam",
    hours: "09:00 - 21:00",
    crowdStatus: "sedang",
    mapsUrl: "https://maps.google.com/?q=Satu+Atap+Coworking+Surabaya"
  },
  {
    id: 7,
    name: "Monopole Coffee Lab",
    address: "Jl. Boulevard Famili Utara, Babatan, Wiyung",
    category: "Coffee Shop",
    noiseScore: 2,
    rating: 4.7,
    reviewCount: 1050,
    tags: ["#aesthetic", "#quiet", "#instagramable"],
    photo: "/images/monopole.png",
    isFeatured: true,
    wifi: true, ac: true, powerOutlet: true,
    priceRange: "Rp30-55k",
    hours: "07:30 - 22:00",
    crowdStatus: "sedang",
    mapsUrl: "https://maps.google.com/?q=Monopole+Coffee+Lab+Surabaya"
  },
  {
    id: 8,
    name: "D'Coffee Cup",
    address: "Jl. Lidah Wetan, Lakarsantri",
    category: "Cafe 24 Jam",
    noiseScore: 2,
    rating: 4.5,
    reviewCount: 890,
    tags: ["#24jam", "#work-friendly", "#worth-it"],
    photo: "/images/dcoffeecup.png",
    isFeatured: false,
    wifi: true, ac: true, powerOutlet: true,
    priceRange: "Rp15-35k",
    hours: "24 Jam",
    crowdStatus: "sepi",
    mapsUrl: "https://maps.google.com/?q=D'Coffee+Cup+Surabaya"
  },
  {
    id: 9,
    name: "Second Cup Coffee",
    address: "Jl. Dharmahusada Indah Timur, Mulyorejo",
    category: "Coffee Shop",
    noiseScore: 2,
    rating: 4.6,
    reviewCount: 680,
    tags: ["#quiet", "#cozy", "#work-friendly"],
    photo: "/images/secondcup.png",
    isFeatured: false,
    wifi: true, ac: true, powerOutlet: true,
    priceRange: "Rp25-50k",
    hours: "08:00 - 22:00",
    crowdStatus: "sedang",
    mapsUrl: "https://maps.google.com/?q=Second+Cup+Surabaya+Dharmahusada"
  },
  {
    id: 10,
    name: "The Localist Cafe",
    address: "Jl. Arief Rahman Hakim, Keputih, Sukolilo",
    category: "Cafe & Bistro",
    noiseScore: 2,
    rating: 4.5,
    reviewCount: 540,
    tags: ["#quiet", "#work-friendly", "#cozy"],
    photo: "/images/localist.png",
    isFeatured: false,
    wifi: true, ac: true, powerOutlet: true,
    priceRange: "Rp20-45k",
    hours: "10:00 - 22:00",
    crowdStatus: "sepi",
    mapsUrl: "https://maps.google.com/?q=The+Localist+Cafe+Surabaya"
  },
  {
    id: 11,
    name: "Volks Coffee",
    address: "Jl. Raya MERR, Manyar, Sukolilo",
    category: "Coffee Shop",
    noiseScore: 1,
    rating: 4.7,
    reviewCount: 780,
    tags: ["#quiet", "#aesthetic", "#minimalis"],
    photo: "/images/volks.png",
    isFeatured: false,
    wifi: true, ac: true, powerOutlet: true,
    priceRange: "Rp25-50k",
    hours: "08:00 - 23:00",
    crowdStatus: "sedang",
    mapsUrl: "https://maps.google.com/?q=Volks+Coffee+MERR+Surabaya"
  },
  {
    id: 12,
    name: "C2O Library & Collabtive",
    address: "Jl. Dr. Cipto No. 20, Sawahan",
    category: "Library & Coworking",
    noiseScore: 1,
    rating: 4.8,
    reviewCount: 620,
    tags: ["#quiet", "#buku", "#inspiratif"],
    photo: "/images/c2o.png",
    isFeatured: false,
    wifi: true, ac: true, powerOutlet: true,
    priceRange: "Gratis - Rp20k",
    hours: "10:00 - 18:00",
    crowdStatus: "sepi",
    mapsUrl: "https://maps.google.com/?q=C2O+Library+Surabaya"
  },
  {
    id: 13,
    name: "Sult Cafe & Eatery",
    address: "Jl. Arief Rahman Hakim No. 185, Keputih, Sukolilo (Area ITS)",
    category: "Cafe & Eatery",
    noiseScore: 2,
    rating: 4.6,
    reviewCount: 812,
    tags: ["#aesthetic", "#quiet", "#western-food"],
    photo: "/images/sultcafe.png",
    isFeatured: true,
    wifi: true, ac: true, powerOutlet: true,
    priceRange: "Rp30-100k",
    hours: "08:00 - 23:00",
    crowdStatus: "sedang",
    mapsUrl: "https://maps.google.com/?q=Sult+Cafe+Eatery+Surabaya"
  },
  {
    id: 14,
    name: "CW Coffee & Eatery",
    address: "Jl. Arief Rahman Hakim, Keputih (Area ITS)",
    category: "Coffee Shop",
    noiseScore: 3,
    rating: 4.5,
    reviewCount: 940,
    tags: ["#ramai", "#luas", "#mahasiswa"],
    photo: "/images/cwcoffee.png",
    isFeatured: false,
    wifi: true, ac: true, powerOutlet: true,
    priceRange: "Rp15-40k",
    hours: "09:00 - 23:00",
    crowdStatus: "ramai",
    mapsUrl: "https://maps.google.com/?q=CW+Coffee+Eatery+Surabaya"
  },
  {
    id: 15,
    name: "Konoae Warung A La Cafe",
    address: "Jl. Keputih Tegal Timur (Belakang ITS)",
    category: "Cafe 24 Jam",
    noiseScore: 2,
    rating: 4.4,
    reviewCount: 650,
    tags: ["#24jam", "#murah", "#santai"],
    photo: "/images/konoae.png",
    isFeatured: false,
    wifi: true, ac: false, powerOutlet: true,
    priceRange: "Rp10-30k",
    hours: "24 Jam",
    crowdStatus: "sedang",
    mapsUrl: "https://maps.google.com/?q=Konoae+Warung+Surabaya"
  },
  {
    id: 16,
    name: "Titik Koma Dharmawangsa",
    address: "Jl. Dharmawangsa No. 148B (Area UNAIR)",
    category: "Coffee Shop",
    noiseScore: 1,
    rating: 4.8,
    reviewCount: 1100,
    tags: ["#quiet", "#minimalis", "#fokus"],
    photo: "/images/titikkoma.png",
    isFeatured: true,
    wifi: true, ac: true, powerOutlet: true,
    priceRange: "Rp25-50k",
    hours: "07:00 - 02:00",
    crowdStatus: "sepi",
    mapsUrl: "https://maps.google.com/?q=Titik+Koma+Dharmawangsa"
  },
  {
    id: 17,
    name: "Kanthi Coffee and Eatery",
    address: "Jl. Dharmawangsa No. 138A (Area UNAIR)",
    category: "Coffee Shop",
    noiseScore: 2,
    rating: 4.6,
    reviewCount: 760,
    tags: ["#cozy", "#mahasiswa-friendly"],
    photo: "/images/kanthi.png",
    isFeatured: false,
    wifi: true, ac: true, powerOutlet: true,
    priceRange: "Rp15-40k",
    hours: "10:00 - 23:00",
    crowdStatus: "sedang",
    mapsUrl: "https://maps.google.com/?q=Kanthi+Coffee+Dharmawangsa"
  },
  {
    id: 18,
    name: "Roemah Kita Cafe",
    address: "Jl. Kedung Sroko No. 123 (Area UNAIR)",
    category: "Cafe & Resto",
    noiseScore: 2,
    rating: 4.5,
    reviewCount: 520,
    tags: ["#luas", "#meeting-room", "#klasik"],
    photo: "/images/roemahkita.png",
    isFeatured: false,
    wifi: true, ac: true, powerOutlet: true,
    priceRange: "Rp20-50k",
    hours: "09:00 - 22:00",
    crowdStatus: "sepi",
    mapsUrl: "https://maps.google.com/?q=Roemah+Kita+Cafe+Surabaya"
  }
];

export const featuresData = [
  { icon: "🔍", title: "Pencarian & Filter Cerdas", desc: "Filter berdasarkan noise level, WiFi, colokan listrik, AC, indoor/outdoor, harga, dan jam buka." },
  { icon: "📍", title: "Detail Tempat Lengkap", desc: "Foto gallery, peta lokasi, noise score visual, badge fasilitas, dan ambience tags." },
  { icon: "⭐", title: "Review & Rating Komunitas", desc: "Rating khusus untuk kebisingan, WiFi, kenyamanan, dan fasilitas. Upload foto dan tag suasana." },
  { icon: "🧭", title: "Rekomendasi Personal", desc: "Dapatkan rekomendasi tempat berdasarkan preferensi ketenangan, tipe tempat, dan kebiasaanmu." },
  { icon: "👤", title: "Profil & Favorit", desc: "Simpan tempat favorit, lihat riwayat review, dan atur preferensi noise & ambience." },
  { icon: "🏢", title: "Dashboard Mitra B2B", desc: "Kelola listing, promosi berbayar, dan pantau statistik pengunjung untuk pemilik cafe." }
];

export const testimonialsData = [
  { id: 1, name: "Aisyah R.", role: "Mahasiswa ITS Surabaya", initial: "A", text: "QuietSpace bantu banget cari tempat nugas di sekitar Keputih. NugaSpace dan Volks Coffee jadi langganan saya sekarang!" },
  { id: 2, name: "Budi S.", role: "Freelance Designer, Surabaya", initial: "B", text: "Sebagai freelancer, WiFi kencang dan colokan itu wajib. Filter di QuietSpace sangat membantu saya menemukan tempat kerja yang perfect di Surabaya." },
  { id: 3, name: "Citra M.", role: "Remote Worker, Surabaya Barat", initial: "C", text: "Fitur noise level indicator itu game changer! Saya bisa pilih antara Monopole yang tenang atau AADK yang lebih lively sesuai mood." }
];

export function getNoiseInfo(score) {
  if (score <= 1) return { label: "Sangat Sunyi", color: "#2D6A4F", bars: [12, 8, 5] };
  if (score <= 2) return { label: "Sunyi", color: "#52B788", bars: [12, 10, 6] };
  if (score <= 3) return { label: "Sedang", color: "#F59E0B", bars: [12, 12, 8] };
  return { label: "Ramai", color: "#EF4444", bars: [12, 12, 12] };
}
